export const filterOptions1 = [
  { name: "Name/Contact No/Email", type: "input", value: "" },
  { name: "Status", type: "options", value: [] },
  { name: "Configuration", type: "options", value: [] },
  { name: "Home Location", type: "search", value: [] },
  { name: "Location Intent", type: "search", value: [] },
  { name: "Locality", type: "search", value: [] },
  { name: "Project", type: "search", value: [] },
  { name: "Possession", type: "options", value: [] },
  { name: "Type", type: "radio", value: [], options: ["Sell", "Rent"] },
  { name: "CSOP", type: "radio", value: [], options: ["Yes", "No"] },
  { name: "Budget", type: "budget", value: [] },
  { name: "Label", type: "options", value: [] },
  { name: "Requirements", type: "options", value: [] },
  { name: "Source", type: "search", value: [] },
  { name: "Sub Source", type: "search", value: [] },
  { name: "FU Action", type: "radio", value: [], options: ["Yes", "No"] },
  { name: "FU Status", type: "radio", value: [], options: ["Yes", "No"] },
  { name: "Follow Up Date", type: "daterange", value: [] },
  { name: "SV Action", type: "radio", value: [], options: ["Yes", "No"] },
  { name: "SV Status", type: "options", value: [] },
  { name: "Site Visit Date", type: "daterange", value: [] },
  { name: "SV Sourcing", type: "search", value: [] },
  { name: "SV Done By", type: "search", value: [] },
  { name: "SV Closed By", type: "search", value: [] },
  { name: "Updated On", type: "daterange", value: [] },
  { name: "Added On", type: "daterange", value: [] },
  { name: "Users", type: "search", value: [] },
  { name: "Timeline", type: "options", value: [] },
  { name: "OCR", type: "input", value: "" },
];

export const filterOptions = [
  // input = 2, daterange = 2, search = 7, radio = 2, budget = 1, options = 6, checkbox = 2, special = 1
  // 8 types

  { name: "Name/Contact No.", type: "input", value: "", ddName: "name" },
  { name: "Status", type: "options", value: [], ddName: "status" },
  { name: "Sub-Status", type: "checkbox", value: [], ddName: "sub_status" },
  { name: "Stage", type: "checkbox", value: [], ddName: "stages" },
  { name: "Label", type: "options", value: [], ddName: "labels" },
  { name: "Typology", type: "options", value: [], ddName: "typologies" },
  { name: "Home Location", type: "search", value: [], ddName: "locations" },
  { name: "Location Intent", type: "search", ddName: "locations" },
  { name: "Locality", type: "search", value: [], ddName: "localities" },
  { name: "Projects", type: "search", value: [], ddName: "projects" },
  { name: "Budget", type: "budget", value: [], ddName: "budget" },
  { name: "Timeline", type: "options", value: [], ddName: "timelines" },
  { name: "Source", type: "search", value: [], ddName: "sources" },
  { name: "Sub Source", type: "search", value: [], ddName: "sub_sources" },
  { name: "FU Action", type: "special", value: [], ddName: "fu_action" },
  { name: "OCR", type: "input", value: "", ddName: "ocr" },
  { name: "Requirements", type: "options", value: [], ddName: "requirements" },
  { name: "User Assigned", type: "search", value: [], ddName: "users" },
  { name: "Possession", type: "options", value: [], ddName: "possessions" },
  {
    name: "CSOP",
    type: "radio",
    value: [],
    options: ["Yes", "No"],
    ddName: "csop",
  },
  {
    name: "Type",
    type: "radio",
    value: [],
    options: ["Sell", "Rent"],
    ddName: "type",
  },
  { name: "Updated On", type: "daterange", value: [], ddName: "updated_on" },
  { name: "Added On", type: "daterange", value: [], ddName: "added_on" },
];

export const financeFilters = [
  { name: "Name/Contact No.", type: "input" },
  { name: "Projects", type: "search" },
  { name: "Configuration", type: "options" },
  { name: "OB Status", type: "options" },
  { name: "Sourced By", type: "search" },
  { name: "Closed By", type: "search" },
  { name: "Inv Status", type: "options" },
  { name: "Deal Status", type: "options" },
  { name: "Closure", type: "daterange" },
  { name: "Follow Up", type: "daterange" },
];
